### ISSUE TITLE
在一些情况失效

### ISSUE THREAD

**Issue by 1xiyu** [lzxb/vue-lazy-load-img#1]
<vue-lazy-load-img 
            mode="default"
            :time="300"
            :complete="true"
            :position="{ top: 0, right: 0, bottom: 0, left: 0 }"
             @success="success">          
            <ul>
                <li v-for="item in searchList">            
                    <img :src="'./images/default.png'" :data-src="item.thumb.gif">
                </li>
            </ul>
	 </vue-lazy-load-img>
这种情况无效，而下面这种情况则有效？
          
         <ul>
             <li v-for="item in searchList"> 
 	        <vue-lazy-load-img>           
                    <img :src="'./images/default.png'" :data-src="item.thumb.gif">
                </vue-lazy-load-img>
            </li>
       </ul>

**Comment by lzxb** [comment]
第一种，应该是正确的。晚上回家后我看看

**Comment by 1xiyu** [comment]
thx，另外说明一些额外情况，1 没采用cmd  2 与你demo差别只是数据，数据来源于mounted后的页面初始化 3 return _c('div', [_vm._t("default")], 2) 正常情况下组件编译渲染为<div><img/></div>,承认在多数没问题，我层级多了之后，会出现<div><img/><div></div></div>这种情况。里层div为空。

**Comment by lzxb** [comment]
好的，刚回到家，看一下先

**Comment by lzxb** [comment]
ok了。你再测试一下看看。已经重新更新了

**Comment by 1xiyu** [comment]
fixed #0225

**Comment by jujubone** [comment]
改变数据图片不会更新

         <ul>
            <li v-for="item in listData">
               <vue-lazy-load-img>
                   <img :src="'../image/load-img.png'" :data-src="item">
               </vue-lazy-load-img>
           </li>
        </ul>



          el: '#app',
          data: {
              listData: [
                  'https://m.360buyimg.com/mobilecms/s720x322_jfs/t4516/279/4086119499/76955/6b2daa8f/5909840cN073961d7.jpg!q70.jpg',
                  'https://img1.360buyimg.com/da/jfs/t4543/50/4317986818/46794/1334d53a/590c5f1eN211b7ced.jpg',
                  'https://img1.360buyimg.com/da/jfs/t5182/122/1445910007/60921/c55ebe2e/5910490fN149812a3.jpg'
              ]
          }

vm.listData[0] = "https://m.360buyimg.com/mobilecms/s720x322_jfs/t6295/316/607943639/64345/839378cb/594231fdN8f049ad7.jpg!q70.jpg"

**Comment by lzxb** [comment]
你应该在for循环外面来使用vue-lazy-load-img组件

**Comment by jujubone** [comment]
<vue-lazy-load-img>
            <ul>
                <li v-for="item in listData">
                     <img :src="'../image/load-img.png'" :data-src="item">
                </li>
            </ul>
        </vue-lazy-load-img>

改为这样，图片还是不会更新，打印vm.listData数据是有更新的
还有，假如这样可以用，那么多层循环应该怎么用

**Comment by lzxb** [comment]
你截个dom的节点图给我看看。不管有多少层循环，放到最外层就好了

**Comment by wss610** [comment]
![Uploading QQ截图20170616224912.png…]()

**Comment by jujubone** [comment]
![qq 20170616224734](https://user-images.githubusercontent.com/16313118/27231970-01aa4ee2-52e7-11e7-8283-9b8c2e327087.png)
![qq 20170616224912](https://user-images.githubusercontent.com/16313118/27231977-0936e828-52e7-11e7-8fd9-660e6f81c0f7.png)

**Comment by lzxb** [comment]
complete设置为false

**Comment by jujubone** [comment]
complete 设为false， 图片还是不更新，listData 的数据不管complete有没有设为false，数据都有更新，但图片就是不更新
![qq 20170616234257](https://user-images.githubusercontent.com/16313118/27234038-25a4992c-52ee-11e7-871c-4b620f6ab405.png)
![qq 20170616234145](https://user-images.githubusercontent.com/16313118/27234049-39560f6e-52ee-11e7-832f-509e93ea8751.png)

**Comment by jujubone** [comment]
[script.zip](https://github.com/lzxb/vue-lazy-load-img/files/1081313/script.zip)
这个压缩包是 以下的两个，真不知道是哪里问题，您是原作者会更清楚一些，求求
<script src="../script/lazy-load-img.js"></script>
<script src="../script/vue-lazy-load-img.js"></script>

**Comment by lzxb** [comment]
从理论上complete设置为false，程序就会一直检测页面的。你可以发我一个完整的demo吗？我晚上调试一下

**Comment by jujubone** [comment]
[demo.zip](https://github.com/lzxb/vue-lazy-load-img/files/1082603/demo.zip)

**Comment by lzxb** [comment]
你应该要这样设置
```javascript
Vue.set(self.listData, 0, 'https://m.360buyimg.com/mobilecms/s720x322_jfs/t6295/316/607943639/64345/839378cb/594231fdN8f049ad7.jpg!q70.jpg')

```

**Comment by lzxb** [comment]
bug修复了，你需要重新安装`lazy-load-img`和`vue-lazy-load-img`，另外设置done参数为false
