### ISSUE TITLE
例子里面的代码写错了

### ISSUE THREAD

**Issue by yzqiang** [lzxb/vue-lazy-load-img#2]
mode-default.html和mode-diy.html里面的complete应该是done，complete是错的。
另外，如果done设置成true，图片会经常加载不进来。

**Comment by lzxb** [comment]
例子已经修复
done：页面内所有数据图片加载完成后，是否自己销毁程序，true默认销毁，false不销毁

**Comment by yzqiang** [comment]
请教一下，为什么done设置为true就无法加载图片呢？

**Comment by lzxb** [comment]
程序已经销毁了，怎么还会加载图片？
